kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 3000/tcp
  Application: app
  Project: database
  Name: hello-react
  Envs:
  - Name: NODE_ENV
    Value: production
  Url:
  - Name: hello-react-3000
    Port: 3000
